#!/bin/bash

# Global parameters
export TENANT_NAME=
export TENANT_ID=
export SUBSCRIPTION_ID=
export RESOURCE_GROUP=
export LOCATION=

# Virtual Network
export VIRTUAL_NETWORK_NAME=
export VIRTUAL_NETWORK_SUBNET_NAME=
export INCLUDE_DATABASE_IN_VIRTUAL_NETWORK=

# Database
export DATABASE_SERVER_NAME=
export DATABASE_ADMIN_USER=
export DATABASE_NAME=
export DATABASE_SKU_CAPACITY=
export DATABASE_SKU_NAME=
export DATABASE_SKU_SIZE_MB=
export DATABASE_SKU_TIER=
export DATABASE_SKU_FAMILY=
export DATABASE_BACKUP_RETENTION_DAYS=
export DATABASE_GEO_REDUNDANT_BACKUP=

# Container Registry
export CONTAINER_REGISTRY_NAME=
export CONTAINER_REGISTRY_SKU=
export PHP_FPM_IMAGE_NAME=
export SUPERVISORD_IMAGE_NAME=
export REDIS_IMAGE_NAME=

# Storage Account
export STORAGE_ACCOUNT_NAME=
export STORAGE_ACCOUNT_SKU=
export STORAGE_ACCOUNT_KIND=
export STORAGE_ACCOUNT_ACCESS_TIER=
export STORAGE_ACCOUNT_CONTAINER_NAME=

# Container Apps
export CONTAINER_APPS_ENVIRONMENT_NAME=pimcore-dev
export PHP_FPM_CONTAINER_APP_NAME=pimcore-php-fpm-dev
export SUPERVISORD_CONTAINER_APP_NAME=pimcore-supervisord-dev
export REDIS_CONTAINER_APP_NAME=pimcore-redis-dev
export APP_DEBUG=1
export APP_ENV=dev
export PIMCORE_DEV=1
export PIMCORE_ENVIRONMENT=dev
export REDIS_DB=12
export REDIS_SESSION_DB=14