name: Tear down Azure resources when PR is closed

on:
  pull_request:
    types: closed
  workflow_dispatch:
  workflow_call:
    inputs:
      SERVICE_PRINCIPAL_ID:
        required: true
        type: string
        description: "Azure Service Principal ID with permissions to deploy resources to the target subscription and resource group"
      DOCKER_COMPOSE_FILE:
        required: true
        type: string
        description: "Path to the Docker Compose file to use for provisioning the Azure environment"
      AZURE_DOCKER_COMPOSE_SERVICE:
        required: false
        type: string
        description: "Name of the service in the Docker Compose file that is used for running Azure CLI commands"
      PARAMETERS_FILE:
        required: true
        type: string
        description: "Path to the parameters file containing the necessary parameters for provisioning the Azure environment"
    secrets:
      SERVICE_PRINCIPAL_PASSWORD:
        required: true
        description: "Azure Service Principal password"

concurrency:
  group: ${{ github.repository }}__${{ github.ref }}-ci-close
  cancel-in-progress: true

jobs:
  tear-down-azure-resources:
    name: Tear down CI Azure resources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Get workflow version
        id: workflow-version
        uses: canonical/get-workflow-version-action@v1
        with:
          repository-name: TorqIT/pimcore-azure-provisioning
          file-name: ci-close.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout workflow repository to use composite actions
        uses: actions/checkout@v6
        with:
          repository: TorqIT/pimcore-azure-provisioning
          ref: ${{ steps.workflow-version.outputs.sha }}
          path: reusable-workflow
          fetch-depth: 1

      - name: Build and start container, and log in to Azure
        uses: ./reusable-workflow/.github/actions/build-start-and-login
        with:
          SERVICE_PRINCIPAL_ID: ${{ vars.SERVICE_PRINCIPAL_ID || inputs.SERVICE_PRINCIPAL_ID }}
          SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
          DOCKER_COMPOSE_FILE: ${{ inputs.DOCKER_COMPOSE_FILE || './.github/ci/docker-compose.yml' }}
          PARAMETERS_FILE: ${{ inputs.PARAMETERS_FILE || './.github/ci/parameters.json' }}
          AZURE_DOCKER_COMPOSE_SERVICE: ${{ inputs.AZURE_DOCKER_COMPOSE_SERVICE || 'azure' }}

      - name: Delete Resource Group
        continue-on-error: true
        run: |
          touch .env
          RESOURCE_GROUP=$(jq -r '.parameters.resourceGroupName.value' ${{ inputs.PARAMETERS_FILE || './.github/ci/parameters.json' }}) >> .env
          docker compose \
            --file ${{ inputs.DOCKER_COMPOSE_FILE || './.github/ci/docker-compose.yml' }} \
            exec ${{ inputs.AZURE_DOCKER_COMPOSE_SERVICE || 'azure' }} \
              az group delete \
                --name $RESOURCE_GROUP \
                --yes

      - name: Purge Key Vault
        run: |
          KEY_VAULT=$(jq -r '.parameters.keyVaultName.value' ${{ inputs.PARAMETERS_FILE || './.github/ci/parameters.json' }}) >> .env
          docker compose \
            --file ${{ inputs.DOCKER_COMPOSE_FILE || './.github/ci/docker-compose.yml' }} \
            exec ${{ inputs.AZURE_DOCKER_COMPOSE_SERVICE || 'azure' }} \
              az keyvault purge \
                --name $KEY_VAULT
