name: CI for a single Pimcore version

on:
  workflow_call:
    inputs:
      GITHUB_ENVIRONMENT:
        required: true
        type: string
        description: "The GitHub environment to use when pulling variables and secrets"
      SKELETON_REF:
        required: true
        type: string
        description: "The branch/ref of TorqIT/pimcore-skeleton to deploy"
      PARAMETERS_FILE:
        required: true
        type: string
        description: "The path to the parameters.json file to use when provisioning the Azure environment"
      SERVICE_PRINCIPAL_ID:
        required: true
        type: string
        description: "Azure Service Principal ID"
    secrets:
      SERVICE_PRINCIPAL_PASSWORD:
        required: true
      PIMCORE_ENCRYPTION_SECRET:
        required: true
      PIMCORE_PRODUCT_KEY:
        required: true
      PIMCORE_INSTANCE_IDENTIFIER:
        required: true
      GH_APP_ID:
        required: true
      GH_APP_PRIVATE_KEY:
        required: true

jobs:
  provision:
    name: Provision Azure environment
    uses: ./.github/workflows/provision-azure-environment.yml
    with:
      SERVICE_PRINCIPAL_ID: ${{ inputs.SERVICE_PRINCIPAL_ID }}
      ENVIRONMENT: ${{ inputs.GITHUB_ENVIRONMENT }}
      SKIP_IF_EXISTS: false
      PARAMETERS_FILE: ${{ inputs.PARAMETERS_FILE }}
      BUILD_IMAGE: true
    secrets:
      SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
      PIMCORE_ENCRYPTION_SECRET: ${{ secrets.PIMCORE_ENCRYPTION_SECRET }}
      PIMCORE_PRODUCT_KEY: ${{ secrets.PIMCORE_PRODUCT_KEY }}
      PIMCORE_INSTANCE_IDENTIFIER: ${{ secrets.PIMCORE_INSTANCE_IDENTIFIER }}

  deploy-skeleton:
    name: Deploy Pimcore Skeleton to Azure Container Apps
    needs: [provision]
    uses: TorqIT/pimcore-github-actions-workflows/.github/workflows/deploy-to-azure-container-apps.yml@v7
    with:
      ENVIRONMENT: ${{ inputs.PARAMETERS_FILE }}
      PROJECT_REPOSITORY: TorqIT/pimcore-skeleton
      PROJECT_REPOSITORY_REF: ${{ inputs.SKELETON_REF }}
      GITHUB_APP_CHECKOUT: true
    secrets:
      SERVICE_PRINCIPAL_ID: ${{ inputs.SERVICE_PRINCIPAL_ID }}
      SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
      PIMCORE_ENCRYPTION_SECRET: ${{ secrets.PIMCORE_ENCRYPTION_SECRET }}
      PIMCORE_PRODUCT_KEY: ${{ secrets.PIMCORE_PRODUCT_KEY }}
      PIMCORE_INSTANCE_IDENTIFIER: ${{ secrets.PIMCORE_INSTANCE_IDENTIFIER }}
      GITHUB_APP_ID: ${{ secrets.GH_APP_ID }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}

  post-url:
    name: Post Container App URL to PR
    needs: [deploy-skeleton]
    uses: ./.github/workflows/post-container-app-url-to-pr.yml
    with:
      ENVIRONMENT: ${{ inputs.GITHUB_ENVIRONMENT }}
      PARAMETERS_FILE: ${{ inputs.PARAMETERS_FILE }}
      SERVICE_PRINCIPAL_ID: ${{ inputs.SERVICE_PRINCIPAL_ID }}
      BUILD_IMAGE: true
    secrets:
      SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
      PIMCORE_ENCRYPTION_SECRET: ${{ secrets.PIMCORE_ENCRYPTION_SECRET }}
      PIMCORE_PRODUCT_KEY: ${{ secrets.PIMCORE_PRODUCT_KEY }}
      PIMCORE_INSTANCE_IDENTIFIER: ${{ secrets.PIMCORE_INSTANCE_IDENTIFIER }}
