name: Provision Azure Environment for Pimcore

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
        description: "The GitHub environment to use for deployment"
      DOCKER_COMPOSE_FILE:
        required: true
        type: string
        description: "Path to the Docker Compose file to use for provisioning the Azure environment"
      AZURE_DOCKER_COMPOSE_SERVICE:
        required: false
        type: string
        default: "azure"
        description: "Name of the service in the Docker Compose file that is used for running Azure CLI commands"
      PARAMETERS_FILE:
        required: true
        type: string
        description: "Path to the parameters file containing the necessary parameters for provisioning the Azure environment"
      SERVICE_PRINCIPAL_ID:
        required: true
        type: string
        description: "Azure Service Principal ID with permissions to deploy resources to the target subscription and resource group"
      SKIP_IF_EXISTS:
        required: false
        type: boolean
        default: true
        description: "Whether to skip provisioning if the Azure environment already exists"
    secrets:
      SERVICE_PRINCIPAL_PASSWORD:
        required: true
        description: "Azure Service Principal password"
      PIMCORE_ENCRYPTION_SECRET:
        required: true
        description: "Secret value for Pimcore encryption, which will be stored in Azure Key Vault"
      PIMCORE_PRODUCT_KEY:
        required: true
        description: "Pimcore product key, which will be stored in Azure Key Vault"
      PIMCORE_INSTANCE_IDENTIFIER:
        required: true
        description: "Pimcore instance identifier, which will be stored in Azure Key Vault"

jobs:
  provision-azure-env:
    name: Provision Azure environment
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Get workflow version
        id: workflow-version
        uses: canonical/get-workflow-version-action@b21f2a1dad0467fd79081fa16dad4f4935fc6253 # v1
        with:
          repository-name: TorqIT/pimcore-azure-provisioning
          file-name: provision-azure-environment.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout workflow repository to use composite actions
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          repository: TorqIT/pimcore-azure-provisioning
          ref: ${{ steps.workflow-version.outputs.sha }}
          path: reusable-workflow
          fetch-depth: 1

      - name: Build and start container, and log in to Azure
        uses: ./reusable-workflow/.github/actions/build-start-and-login
        with:
          SERVICE_PRINCIPAL_ID: ${{ inputs.SERVICE_PRINCIPAL_ID }}
          SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
          PARAMETERS_FILE: ${{ inputs.PARAMETERS_FILE }}
          DOCKER_COMPOSE_FILE: ${{ inputs.DOCKER_COMPOSE_FILE }}
          AZURE_DOCKER_COMPOSE_SERVICE: ${{ inputs.AZURE_DOCKER_COMPOSE_SERVICE }}

      # TODO this should ideally be a script in the container itself
      - name: Provision the Azure environment
        id: deploy
        run: |
          mv "${{ inputs.PARAMETERS_FILE }}" parameters.json
          docker compose \
            --file ${{ inputs.DOCKER_COMPOSE_FILE }} \
            exec ${{ inputs.AZURE_DOCKER_COMPOSE_SERVICE }} \
            bash -c \
            '
              set -e

              resourceGroup=$(jq -r ".parameters.resourceGroupName.value" parameters.json)

              if [ $(az group exists --name $resourceGroup) == 'true' ] &&
                 [ ${{ inputs.SKIP_IF_EXISTS }} == 'true' ]; then
                echo "Resource Group $resourceGroup already exists, skipping provisioning as SKIP_IF_EXISTS is set to true."
              else
                echo "Creating Resource Group $resourceGroup..."
                location=$(jq -r ".parameters.location.value" parameters.json)
                az group create --name $resourceGroup --location $location

                echo "Creating Key Vault..."
                ./provisioning-scripts/provision-key-vault.sh parameters.json

                echo "Setting required Pimcore secrets in Key Vault..."
                keyVaultName=$(jq -r ".parameters.keyVaultName.value" parameters.json)
                keyVaultResourceGroupName=$(jq -r --arg RESOURCE_GROUP "$resourceGroup" ".parameters.keyVaultResourceGroupName.value // \$RESOURCE_GROUP" parameters.json)
                az keyvault network-rule add \
                    --name $keyVaultName \
                    --resource-group $keyVaultResourceGroupName \
                    --ip-address $(curl ipinfo.io/ip)
                az keyvault secret set \
                    --vault-name $keyVaultName \
                    --name "pimcore-encryption-secret" \
                    --value "${{ secrets.PIMCORE_ENCRYPTION_SECRET }}"
                az keyvault secret set \
                    --vault-name $keyVaultName \
                    --name "pimcore-product-key" \
                    --value "${{ secrets.PIMCORE_PRODUCT_KEY }}"
                az keyvault secret set \
                    --vault-name $keyVaultName \
                    --name "pimcore-instance-identifier" \
                    --value "${{ secrets.PIMCORE_INSTANCE_IDENTIFIER }}"
                az keyvault network-rule remove \
                    --name $keyVaultName \
                    --resource-group $keyVaultResourceGroupName \
                    --ip-address $(curl ipinfo.io/ip)

                ./provision.sh parameters.json
              fi
            '

      - name: Cancel Azure deployment if the deploy step failed or was cancelled
        if: always()
        continue-on-error: true
        run: |
          if [ ${{ steps.deploy.outcome }} == 'failure' ] || [ ${{ steps.deploy.outcome }} == 'cancelled' ]; then
            touch .env
            RESOURCE_GROUP=$(jq -r '.parameters.resourceGroupName.value' ${{ inputs.PARAMETERS_FILE }}) >> .env
            docker compose \
              --file ${{ inputs.DOCKER_COMPOSE_FILE }} \
              exec ${{ inputs.AZURE_DOCKER_COMPOSE_SERVICE }} \
                az deployment group cancel \
                  --resource-group $RESOURCE_GROUP \
                  --name main
          fi
