name: Provision Azure Environment for Pimcore

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
        description: "The GitHub environment to use for deployment"
      PARAMETERS_FILE:
        required: true
        type: string
        description: "Path to the parameters file containing the necessary parameters for provisioning the Azure environment"
      SERVICE_PRINCIPAL_ID:
        required: true
        type: string
        description: "Azure Service Principal ID with permissions to deploy resources to the target subscription and resource group"
      SKIP_IF_EXISTS:
        required: false
        type: boolean
        default: true
        description: "Whether to skip provisioning if the Azure environment already exists"
      BUILD_IMAGE:
        required: false
        type: boolean
        default: false
        description: "Whether to build the provisioning Docker image before starting the container. Will attempt to use Dockerfile at the root of the project."
    secrets:
      SERVICE_PRINCIPAL_PASSWORD:
        required: true
        description: "Azure Service Principal password"
      PIMCORE_ENCRYPTION_SECRET:
        required: true
        description: "Secret value for Pimcore encryption, which will be stored in Azure Key Vault"
      PIMCORE_PRODUCT_KEY:
        required: true
        description: "Pimcore product key, which will be stored in Azure Key Vault"
      PIMCORE_INSTANCE_IDENTIFIER:
        required: true
        description: "Pimcore instance identifier, which will be stored in Azure Key Vault"

jobs:
  provision-azure-env:
    name: Provision Azure environment
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Get workflow version
        id: workflow-version
        uses: canonical/get-workflow-version-action@ba22d0abdc1eda539aa3ac81af1cfee160b10714 # v1
        with:
          repository-name: TorqIT/pimcore-azure-provisioning
          file-name: provision-azure-environment.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout workflow repository to use composite actions
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          repository: TorqIT/pimcore-azure-provisioning
          ref: ${{ steps.workflow-version.outputs.sha }}
          path: reusable-workflow
          fetch-depth: 1

      - name: Build and start container, and log in to Azure
        uses: ./reusable-workflow/.github/actions/build-start-and-login
        with:
          SERVICE_PRINCIPAL_ID: ${{ inputs.SERVICE_PRINCIPAL_ID }}
          SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
          PARAMETERS_FILE: ${{ inputs.PARAMETERS_FILE }}
          BUILD_IMAGE: "${{ inputs.BUILD_IMAGE }}"

      # TODO this should ideally be a script in the container itself
      - name: Provision the Azure environment
        id: deploy
        run: |
          docker exec azure bash -c '
            set -e

            resourceGroup=$(jq -r ".parameters.resourceGroupName.value" parameters.json)

            if [ $(az group exists --name $resourceGroup) == 'true' ] &&
                [ ${{ inputs.SKIP_IF_EXISTS }} == 'true' ]; then
              echo "Resource Group $resourceGroup already exists, skipping provisioning as SKIP_IF_EXISTS is set to true."
            else
              echo "Creating Resource Group $resourceGroup..."
              location=$(jq -r ".parameters.location.value" parameters.json)
              az group create --name $resourceGroup --location $location

              echo "Creating Key Vault..."
              ./provisioning-scripts/provision-key-vault.sh parameters.json

              echo "Setting required Pimcore secrets in Key Vault..."
              keyVaultName=$(jq -r ".parameters.keyVaultName.value" parameters.json)
              keyVaultResourceGroupName=$(jq -r --arg RESOURCE_GROUP "$resourceGroup" ".parameters.keyVaultResourceGroupName.value // \$RESOURCE_GROUP" parameters.json)
              az keyvault network-rule add \
                --name $keyVaultName \
                --resource-group $keyVaultResourceGroupName \
                --ip-address $(curl ipinfo.io/ip)
              az keyvault secret set \
                --vault-name $keyVaultName \
                --name "pimcore-encryption-secret" \
                --value "${{ secrets.PIMCORE_ENCRYPTION_SECRET }}"
              az keyvault secret set \
                --vault-name $keyVaultName \
                --name "pimcore-product-key" \
                --value "${{ secrets.PIMCORE_PRODUCT_KEY }}"
              az keyvault secret set \
                --vault-name $keyVaultName \
                --name "pimcore-instance-identifier" \
                --value "${{ secrets.PIMCORE_INSTANCE_IDENTIFIER }}"
              az keyvault network-rule remove \
                --name $keyVaultName \
                --resource-group $keyVaultResourceGroupName \
                --ip-address $(curl ipinfo.io/ip)

              ./provision.sh parameters.json
            fi
          '

      - name: Clean up Docker artifacts
        if: always()
        continue-on-error: true
        run: |
          docker rm -f azure
          docker image prune -af

      - name: Cancel Azure deployment if the deploy step failed or was cancelled
        if: always()
        continue-on-error: true
        run: |
          if [ ${{ steps.deploy.outcome }} == 'failure' ] || [ ${{ steps.deploy.outcome }} == 'cancelled' ]; then
            touch .env
            RESOURCE_GROUP=$(jq -r '.parameters.resourceGroupName.value' ${{ inputs.PARAMETERS_FILE }}) >> .env
            docker exec azure bash -c '
              az deployment group cancel \
                --resource-group $RESOURCE_GROUP \
                --name main
            '
          fi
